import {fonts} from './Font';
import {DEVICE_WIDTH, DEVICE_HEIGHT} from './device-info';
import {
  swiper,
  brand,
  size,
  backLight,
  specialOffer,
  colorArray,
  categories,
} from './constAray';
import {
  baseWidth,
  baseSidesSpace,
  containerVerticalSpace,
  mediumRadius,
  largeRadius,
  extraLargeRadius,
  smallShadow,
  mediumShadow,
  baseLineHeight,
  baseTouchOpacity,
  headerHeight,
  headerPaddingHorizontal,
  toastOption,
} from './common';
export {
  fonts,
  DEVICE_WIDTH,
  DEVICE_HEIGHT,
  swiper,
  brand,
  size,
  backLight,
  specialOffer,
  colorArray,
  categories,
  baseWidth,
  baseSidesSpace,
  containerVerticalSpace,
  mediumRadius,
  largeRadius,
  extraLargeRadius,
  smallShadow,
  mediumShadow,
  baseLineHeight,
  baseTouchOpacity,
  headerHeight,
  headerPaddingHorizontal,
  toastOption,
};
